#!/usr/bin/env bash
# ────────────────────────────────────────────────────────────────────────────
# CIRA GitHub Actions context relay
#
# This script loads CIRA context from artifacts and injects it into
# the current CI session. Designed for use in GitHub Actions workflows
# where AI coding agents (Claude Code, etc.) need context from previous
# runs or from developer sessions.
# ────────────────────────────────────────────────────────────────────────────
set -euo pipefail

CIRA_DIR="${CIRA_DIR:-.cira}"
CONTEXT_FILE="$CIRA_DIR/context.md"

# ── Load context from artifact ─────────────────────────────────────────────

if [[ -f "$CONTEXT_FILE" ]]; then
  echo "==> CIRA: Loading context from $CONTEXT_FILE"
  cat "$CONTEXT_FILE"
else
  echo "==> CIRA: No context file found at $CONTEXT_FILE"
fi

# ── Save context as artifact (called at end of workflow) ───────────────────

save_context() {
  mkdir -p "$CIRA_DIR"
  # Generate a context summary from the current session
  # In CI, this would capture Git diff, PR description, etc.
  cat > "$CONTEXT_FILE" << EOF
# CIRA Context Dump
Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
Repository: $GITHUB_REPOSITORY
Branch: $GITHUB_REF_NAME
Commit: $GITHUB_SHA

## PR / Commit Info
$(
  if [[ -n "${GITHUB_EVENT_PATH:-}" ]] && [[ -f "$GITHUB_EVENT_PATH" ]]; then
    jq -r '.pull_request // .head_commit | "Title: \(.title // .message)\nBody: \(.body // "")"' "$GITHUB_EVENT_PATH" 2>/dev/null || echo "No PR/commit info"
  fi
)

## Diff Summary
$(
  if [[ -n "${GITHUB_BASE_REF:-}" ]]; then
    echo "Files changed:"
    git diff --name-only "origin/${GITHUB_BASE_REF}...HEAD" 2>/dev/null | head -50 || echo "(not available)"
  fi
)

## CIRA Handoff
This context was auto-generated by a CI pipeline. Continue working on this
codebase with the context above. Focus on the changes described.
EOF
  echo "==> CIRA: Context saved to $CONTEXT_FILE"
}

# If called with --save, save context
if [[ "${1:-}" == "--save" ]]; then
  save_context
fi
